---
- name: Set done to false
  set_fact:
    apt_conf_list_entry_done: False

- name: Get files containing this entry
  find:
    contains: '{{ list_item.key }}'
    file_type: file
    paths: /etc/apt
#   patterns: '([0-9]{2}.*|apt.conf$)'
    recurse: True
#   use_regex: True
  register: register_apt_conf_found_files

- name: Check found files
  include: apt-conf-file.yml
  with_items: '{{ register_apt_conf_found_files.files }}'
  loop_control:
    loop_var: found_file
  when: register_apt_conf_found_files.matched > 0 and
        ( found_file.path == '/etc/apt/apt.conf' or
          found_file.path | search('/etc/apt/apt.conf.d/') )

- name: Add entry (no file found with entry)
  lineinfile:
    create: True
    owner: root
    group: root
    mode: '0644'
    state: present
    line: '{{ list_item.key }} {{ list_item.value }}'
    dest: '{{ list_item.path|default(apt_conf_config_file) }}'
  when: list_item.enable
