---
- name: Iterate list entries
  include: apt-conf-list-entry.yml
  with_items: '{{ apt_conf_entries }}'
  loop_control:
    loop_var: list_item
  when: ansible_os_family == 'Debian'
  tags:
    - apt-conf
